export { CREATE_POST_FIRST_LEVEL_COMMENT, CREATE_POST_SECOND_LEVEL_COMMENT } from './mutation';
export {
	CREATE_COMMENT_FEED,
	CREATE_COMMENT_REPLY,
	CREATE_REACTION,
	GET_COMMENTS,
	GET_COMPANY_POST,
	GET_POST_FIRST_LEVEL_COMMENTS,
	GET_POST_FOLLOWED_BY_USER,
	GET_POST_SECOND_LEVEL_COMMENTS,
	GET_REACTIONS_POST,
	REACTIONS,
} from './resolver';
