export {
	CREATE_COMMUNITY,
	GET_COMMUNITY,
	GET_COMMUNITY_BY_ID,
	COMMUNITY_POLICIES,
	COMMUNITY_POLICY,
	CREATE_COMMUNITY_POLICY,
	UPDATE_COMMUNITY_POLICY,
	DELETE_COMMUNITY_POLICY,
} from './resolver';
