export {
	CREATE_COMMUNITY,
	COMMUNITY_POLICIES,
	COMMUNITY_POLICY,
	CREATE_COMMUNITY_POLICY,
	UPDATE_COMMUNITY_POLICY,
	DELETE_COMMUNITY_POLICY,
	GET_COMMUNITIES,
	GET_COMMUNITIES_BY_ID,
	EDIT_COMMUNITY,
} from './resolver';
